import type { Agent, Command } from '@/types/agents'
import type { Lead, Client } from '@/types/crm'
import type { Metric, Automation, Task, SystemLogEntry } from '@/types/os'

export const AGENTS: Agent[] = [
  {
    id: 'orchestrator',
    name: 'Central Orchestrator',
    description: 'Clasifica comandos y enruta al agente correcto',
    status: 'ACTIVE',
    color: '#C4922A',
    icon: '⚡',
    capabilities: ['routing', 'classification', 'intent-detection'],
  },
  {
    id: 'sales',
    name: 'Veloxia Sales',
    description: 'Propuestas, scripts, outreach, objeciones',
    status: 'STANDBY',
    color: '#FF6A00',
    icon: '💼',
    capabilities: ['proposals', 'scripts', 'cold-outreach', 'objections'],
    lastUsed: '14:32',
  },
  {
    id: 'builder',
    name: 'Veloxia Builder',
    description: 'Web, código, Claude Code prompts, arquitectura',
    status: 'STANDBY',
    color: '#4AFF8A',
    icon: '🏗️',
    capabilities: ['code', 'web', 'architecture', 'claude-prompts'],
    lastUsed: '11:20',
  },
  {
    id: 'ops',
    name: 'Veloxia Ops',
    description: 'CRM, tareas, seguimientos, proyectos',
    status: 'STANDBY',
    color: '#60A5FA',
    icon: '⚙️',
    capabilities: ['crm', 'tasks', 'follow-ups', 'projects'],
    lastUsed: '09:45',
  },
  {
    id: 'content',
    name: 'Veloxia Content',
    description: 'Reels, posts, hooks, captions, calendarios',
    status: 'STANDBY',
    color: '#E879F9',
    icon: '🎬',
    capabilities: ['reels', 'posts', 'hooks', 'captions', 'calendars'],
    lastUsed: '13:10',
  },
  {
    id: 'mortgage',
    name: 'Mortgage Assistant',
    description: 'Hipotecas, emails a bancos, explicaciones a clientes',
    status: 'STANDBY',
    color: '#34D399',
    icon: '🏦',
    capabilities: ['mortgage-comparison', 'bank-emails', 'client-explanations'],
    lastUsed: 'Ayer',
  },
  {
    id: 'personal',
    name: 'Personal Assistant',
    description: 'Planificación diaria, prioridades, notas, recordatorios',
    status: 'STANDBY',
    color: '#FBBF24',
    icon: '🗓️',
    capabilities: ['planning', 'priorities', 'notes', 'reminders'],
    lastUsed: '08:00',
  },
]

export const METRICS: Metric[] = [
  { id: 'leads', label: 'Leads hoy', value: 7, delta: '+3', trend: 'up' },
  { id: 'proposals', label: 'Propuestas generadas', value: 2, delta: '+1', trend: 'up' },
  { id: 'meetings', label: 'Reuniones agendadas', value: 3, delta: '=', trend: 'neutral' },
  { id: 'automations', label: 'Automatizaciones activas', value: 12, delta: '+2', trend: 'up' },
  { id: 'response_time', label: 'Tiempo respuesta IA', value: '1.2s', delta: '-0.3s', trend: 'up' },
  { id: 'pipeline', label: 'Pipeline estimado', value: '€28,400', delta: '+€4k', trend: 'up' },
]

export const LEADS: Lead[] = [
  {
    id: 'l1',
    name: 'Clínica Estética Luminos',
    email: 'info@luminos.es',
    phone: '+34 611 000 001',
    business_type: 'Clínica estética',
    city: 'Madrid',
    status: 'proposal',
    revenue_potential: 4800,
    source: 'Instagram',
    created_at: '2026-05-12',
    last_contact: '2026-05-13',
  },
  {
    id: 'l2',
    name: 'Fitness Premium BCN',
    email: 'hola@fitpremium.es',
    phone: '+34 622 000 002',
    business_type: 'Fitness boutique',
    city: 'Barcelona',
    status: 'qualified',
    revenue_potential: 3200,
    source: 'Vault',
    created_at: '2026-05-11',
    last_contact: '2026-05-12',
  },
  {
    id: 'l3',
    name: 'Despacho Sánchez & Partners',
    email: 'contacto@sanchezlaw.es',
    phone: '+34 633 000 003',
    business_type: 'Despacho legal',
    city: 'Madrid',
    status: 'contacted',
    revenue_potential: 6000,
    source: 'Referido',
    created_at: '2026-05-10',
  },
  {
    id: 'l4',
    name: 'Inmobiliaria Lujo Madrid',
    email: 'info@luxomadrid.es',
    phone: '+34 644 000 004',
    business_type: 'Inmobiliaria lujo',
    city: 'Madrid',
    status: 'new',
    revenue_potential: 9600,
    source: 'Diagnóstico',
    created_at: '2026-05-13',
  },
  {
    id: 'l5',
    name: 'Centro Dental Orova',
    email: 'admin@orovadental.es',
    phone: '+34 655 000 005',
    business_type: 'Clínica dental',
    city: 'Valencia',
    status: 'closed',
    revenue_potential: 4200,
    source: 'Google',
    created_at: '2026-04-28',
    last_contact: '2026-05-05',
  },
]

export const CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'Clínica Belleza & Co.',
    email: 'direccion@bellezaco.es',
    phone: '+34 600 111 222',
    business_type: 'Clínica estética',
    city: 'Madrid',
    status: 'closed',
    revenue_potential: 4800,
    source: 'Instagram',
    created_at: '2026-02-01',
    contract_value: 4800,
    services: ['Studio', 'Setter'],
    start_date: '2026-02-15',
  },
]

export const AUTOMATIONS: Automation[] = [
  {
    id: 'a1',
    name: 'Intake Diagnóstico',
    description: 'Captura leads del formulario de diagnóstico y los crea en CRM',
    trigger: 'POST /webhook/diagnostico-intake',
    webhook: 'diagnostico-intake',
    status: 'active',
    runs_today: 4,
    last_run: '14:45',
  },
  {
    id: 'a2',
    name: 'Vault Register',
    description: 'Registra nuevos usuarios del Vault',
    trigger: 'POST /webhook/vault-register',
    webhook: 'vault-register',
    status: 'active',
    runs_today: 11,
    last_run: '15:02',
  },
  {
    id: 'a3',
    name: 'Follow-up 24h',
    description: 'Envía seguimiento automático a leads sin respuesta',
    trigger: 'Cron: cada día 09:00',
    webhook: 'follow-up-trigger',
    status: 'active',
    runs_today: 1,
    last_run: '09:00',
  },
  {
    id: 'a4',
    name: 'Propuesta Automática',
    description: 'Genera propuesta PDF tras llamada de diagnóstico',
    trigger: 'POST /webhook/generate-proposal',
    webhook: 'generate-proposal',
    status: 'paused',
    runs_today: 0,
  },
]

export const TASKS: Task[] = [
  {
    id: 't1',
    title: 'Enviar propuesta a Clínica Luminos',
    description: 'Propuesta Studio + Setter €4,800/año',
    status: 'in_progress',
    priority: 'high',
    agent: 'sales',
    due_date: '2026-05-14',
    created_at: '2026-05-13',
  },
  {
    id: 't2',
    title: 'Crear 3 reels para esta semana',
    description: 'Reels para Veloxia Content: beneficios IA para clínicas',
    status: 'pending',
    priority: 'medium',
    agent: 'content',
    due_date: '2026-05-16',
    created_at: '2026-05-13',
  },
  {
    id: 't3',
    title: 'Seguimiento Fitness Premium BCN',
    status: 'pending',
    priority: 'high',
    agent: 'ops',
    due_date: '2026-05-13',
    created_at: '2026-05-12',
  },
  {
    id: 't4',
    title: 'Actualizar web Veloxia Studio',
    status: 'done',
    priority: 'medium',
    agent: 'builder',
    created_at: '2026-05-10',
  },
]

export const COMMAND_HISTORY: Command[] = [
  {
    id: 'cmd1',
    text: 'Genera una propuesta para una clínica estética en Madrid',
    timestamp: '14:32',
    agent: 'sales',
    response: 'Propuesta generada: Pack Studio + Setter a €4,800/año...',
    duration_ms: 1240,
  },
  {
    id: 'cmd2',
    text: 'Añade como lead a Inmobiliaria Lujo Madrid',
    timestamp: '13:55',
    agent: 'ops',
    response: 'Lead creado en CRM. Potencial: €9,600.',
    duration_ms: 820,
  },
  {
    id: 'cmd3',
    text: 'Crea 5 ideas de contenido para Instagram sobre IA para clínicas',
    timestamp: '13:10',
    agent: 'content',
    response: '5 ideas generadas y guardadas en tu librería...',
    duration_ms: 1890,
  },
]

export const INITIAL_LOGS: SystemLogEntry[] = [
  {
    id: 'log0',
    timestamp: '08:00:00',
    message: 'VELOXIA OS iniciado. Todos los sistemas operativos.',
    type: 'success',
  },
  {
    id: 'log1',
    timestamp: '09:00:00',
    message: 'Automatización Follow-up 24h ejecutada. 3 mensajes enviados.',
    type: 'info',
  },
  {
    id: 'log2',
    timestamp: '13:10:22',
    message: 'Agente activado: Veloxia Content',
    type: 'agent',
  },
  {
    id: 'log3',
    timestamp: '13:55:41',
    message: 'CRM actualizado: nuevo lead creado — Inmobiliaria Lujo Madrid',
    type: 'success',
  },
  {
    id: 'log4',
    timestamp: '14:32:09',
    message: 'Agente activado: Veloxia Sales',
    type: 'agent',
  },
  {
    id: 'log5',
    timestamp: '14:32:10',
    message: 'Propuesta generada para Clínica estética Madrid',
    type: 'success',
  },
  {
    id: 'log6',
    timestamp: '14:45:03',
    message: 'Webhook vault-register: 2 nuevos registros procesados',
    type: 'info',
  },
]
